[versions]
agp = "8.7.2"
godot = "4.3.0.stable"

[libraries]
godot = { group = "org.godotengine", name = "godot", version.ref = "godot" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }

